version: 2

jobs:
  image_build:
    environment:
      IMAGE_NAME: thehubaubg/unimorph-backend
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker build -t $IMAGE_NAME:latest .
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker push $IMAGE_NAME:latest
  
  deployment:
    docker:
      - image: circleci/buildpack-deps:stretch 
    steps:
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "f1:6f:6f:57:9f:96:0e:13:80:60:06:4f:60:e7:44:94"
      - run: ssh $SSH_USER@$SSH_HOST 'docker-compose -f prod/Eureka/docker-compose.yml down && docker-compose -f prod/Eureka/docker-compose.yml pull && docker-compose -f prod/Eureka/docker-compose.yml up -d'

workflows:
      version: 2
      deploy:
        jobs:
          - image_build:
              filters:
                branches:
                  only:
                    - master
          - deployment:
              requires:
                - image_build