version: '3.6'

services:
  backend:
    build: .
    environment:
    - DB_HOST=database
    depends_on:
    - database
    expose:
    - 8000

  frontend:
    image: thehubaubg/unimorph-frontend:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - database
    - backend

  database:
    image: thehubaubg/unimorph-testdb:latest